spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
debug: true
mybatis:
  type-aliases-package: com.hpm.blog.model
  config-location: classpath:mybatis.xml
